plugin-install:
	vagrant plugin install vagrant-itamae

gem-install:
	bundler install

install:gem-install plugin-install

up:
	vagrant up

halt:
	vagrant halt

destroy:
	vagrant destroy

provision:
	vagrant provision

