# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "CentOS-6.6"
  config.vm.box_url = "https://vagrantcloud.com/chef/boxes/centos-6.6/versions/1.0.0/providers/virtualbox.box"

  config.vm.define :web2 do |web|
    web.vm.network :private_network, ip: "192.168.33.102"
    web.vm.provision :shell, :path => 'script/common.sh'
  end
end
